package repository_test

import (
	"fmt"
	"tbox_backend/src/entity"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type IUserRepo struct {
	mock.Mock
}

func (_m *IUserRepo) FindByPhoneNumber(phoneNumber string) (entity.User, error) {
	ret := _m.Called(phoneNumber)

	fmt.Println(ret.Get(0))

	return entity.User{}, nil
}
